languageCode = "en-us"
baseURL = "https://spacelis.github.io"
title = "0x4C"
theme = "hugo-redlounge"
disqusShortname = "0x4C"
googleAnalytics = "UA-43808487-3"
enableRobotsTXT = true

[[menu.posts]]
  name = "Blog"
  url = "/posts"

[params]
  sidebartitle = "0x4C"
  sidebartagline = "SpaceLis' Blog"
